### ISSUE TITLE
GetTime() producing abnormal value for Descant detectors

### ISSUE THREAD

**Issue by smayotte** [GRIFFINCollaboration/NTuple2EventTree#29]
Hi,
after the Griffin meeting this morning we were asked to open a GitHub issue on the problems we've been having with the GetTime() function.

First, here is the context from the email Fred was referring to:

> I found our issue in the timing.  GRSISort handles the timestamp as an integer in the TPPG and TFragment classes, and it so happens our timescale * 1e8 is on integer scales.  I fixed this by scaling by 1e12 to carry 5 sig figures into integer scale for the converter in NTuple2EventTree, then divided by the extra scaling when I took the number out of the tree. 

We are currently also using this implementation in Converter.cc, which was done by changing l. 235 and 246 to
`fFragments[address].SetTimeStamp(fTime*1.0e12);` (we're using a version of NTuple2EventTree from ~2018)

The "garbage value" that Akanksha was referring to is always the same (-9,223,372,036,854,775,808 or −2^63), which is the minimum value of a 64-bit signed integer. I would guess this has some significance.

The most surprising part is that we don't always get garbage values (and none when we are shooting a neutron gun at the central detector), so we will definitely also check out our raw simulations as was suggested in the meeting.

**Comment by VinzenzBildstein** [comment]
Okay, so it seems you made a workaround on the timestamp basis to get higher precision than the 10 ns you get in a GRIF-16 or 2 ns you would get from a VX1730 digitizer. To get better precision on the time the digitizers (both GRIF-16 and VX1730) provide a CFD value (also an integer).

How this CFD value is applied to the timestamp to get a floating point time with better precision depends on the digitizer module:

- For a GRIF-16 the CFD replaces the lowest 18 bits of the timestamp and adds more bits to give a precision of 10/16th of a nanosecond, so we zero the lowest 18 bits of the timestamp and then add the CFD/1.6 to get the time as a floating point number in nanoseconds.
- For a VX1730 (as used to read out DESCANT), the CFD is a 10 bit number that gives an interpolation between two timestamps, i.e. 2 ns. So for data from this digitizer we add the CFD/512. to the timestamp to get the time as a floating point number in nanosecond units.

The Converter class takes the floating point time in seconds as provided by Geant4, and sets the timestamp to time*1e8. This means the timestamp is always set in 10 ns units, which is wrong if we want the data to look like it came from a VX1730. So this general line should be replaced by a case-by-case decision based on the digitizer type used for the detector the data came from.

This is already done for the CFD value, which is set using the Cfd function which takes the digitizer type as an input and returns the CFD in the appropriate format. This function though is a bit outdated and does not have the VX1730 implemented (only GRIF-16, TIG10, and 4G are implemented). Furthermore the converter class always uses a GRIF-16 as a digitizer, no matter which system (detector) the data came from.

So the Converter class right now treats all the data as though it came from a GRIF-16, providing timestamp in 10 ns units and the CFD value in 10/16 ns units. What happens with this data in GRSISort now also depends on the .cal file you use. If the cal-file is set up to treat all data as if it came from GRIF-16 digitizers, the resulting time should still be fine, just with a precision of 10/16 ns instead of 1/512 ns. If however the cal-file (correctly) says that the DESCANT data comes from VX1730 digitizers, then the CFD value would be interpreted wrong and give very weird results (though I'm don't know if it would always return -2^63).

I think the right way would be to update the Converter class to treat data from VX1730 digitizers correctly, and then set it (and the cal-file) up so that DESCANT data is always interpreted as coming from those digitizers.

Your workaround to get better precision requires you to use GetTimeStamp only and not GetTime in GRSISort and to then also divide out the extra multiplication you put in.

**Comment by smayotte** [comment]
Ok, we can use GetTimeStamp I think (we're already dividing out the extra multiplication). 

I am not sure what .cal file we are using, can you tell me were I would find that file?

**Comment by VinzenzBildstein** [comment]
I was wrong, there is not cal-file needed when you use NTuple2EventTree, the converter creates the calibration settings and saves them to the analysis and fragment file. So things are at least handled consistently, though the digitizers used (at least for DESCANT) are not right, but that won't affect your simulations if you continue using your workaround.
